//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULA.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ULA.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! Данная программа защищается законом об авторских правах. Незаконное копирование или распространение этой программы или какой-либо её части может повлечь суровые гражданские или уголовные наказания и будет преследоваться по всей строгости закона..
        /// </summary>
        internal static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип сущности не может быть пустым.
        /// </summary>
        internal static string AomEntityTypeNullTypeExceptionMessage {
            get {
                return ResourceManager.GetString("AomEntityTypeNullTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция типов свойств в нотации AOM не задана.
        /// </summary>
        internal static string AomPropertyNullCollectionExceptionMessage {
            get {
                return ResourceManager.GetString("AomPropertyNullCollectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип свойства не может быть пустым.
        /// </summary>
        internal static string AomPropertyTypeNullPropertyTypeExceptionMessage {
            get {
                return ResourceManager.GetString("AomPropertyTypeNullPropertyTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя свойства не может быть пустым.
        /// </summary>
        internal static string AomPropertyTypePropertyNameExceptionMessage {
            get {
                return ResourceManager.GetString("AomPropertyTypePropertyNameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление Наружным Освещением.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторежим.
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсветка.
        /// </summary>
        internal static string Backlight {
            get {
                return ResourceManager.GetString("Backlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидайте....
        /// </summary>
        internal static string BusyDialogTitle {
            get {
                return ResourceManager.GetString("BusyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие команды.
        /// </summary>
        internal static string CitywideCommandHeader {
            get {
                return ResourceManager.GetString("CitywideCommandHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление командами.
        /// </summary>
        internal static string CitywideCommandsTitle {
            get {
                return ResourceManager.GetString("CitywideCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление по шаблонам.
        /// </summary>
        internal static string CommandOnTemplateTitle {
            get {
                return ResourceManager.GetString("CommandOnTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее.
        /// </summary>
        internal static string CommonDeviceSettings {
            get {
                return ResourceManager.GetString("CommonDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим конфигурации.
        /// </summary>
        internal static string ConfigurationMode {
            get {
                return ResourceManager.GetString("ConfigurationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать виртуальное устройство.
        /// </summary>
        internal static string CreateNewDeviceDialogTitle {
            get {
                return ResourceManager.GetString("CreateNewDeviceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат файла хранилища данных устройства не верен.
        /// </summary>
        internal static string DataStorageFileFormatExceptionMessage {
            get {
                return ResourceManager.GetString("DataStorageFileFormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к хранилищу информации об устройствах задан не верно.
        /// </summary>
        internal static string DataStorageFilePathExceptionMessage {
            get {
                return ResourceManager.GetString("DataStorageFilePathExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string DeleteSelectedDeviceHeader {
            get {
                return ResourceManager.GetString("DeleteSelectedDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство с именем {0} уже существует..
        /// </summary>
        internal static string DeviceAlreadyExistsExceptionMessageFormat {
            get {
                return ResourceManager.GetString("DeviceAlreadyExistsExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание устройства.
        /// </summary>
        internal static string DeviceDescription {
            get {
                return ResourceManager.GetString("DeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание виртуального устройства.
        /// </summary>
        internal static string DeviceDescriptionTooltip {
            get {
                return ResourceManager.GetString("DeviceDescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в устройстве: {0}..
        /// </summary>
        internal static string DeviceExceptionInfoPartMessageFormat {
            get {
                return ResourceManager.GetString("DeviceExceptionInfoPartMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена ошибка при работе с устройством..
        /// </summary>
        internal static string DeviceExceptionSimpleMessage {
            get {
                return ResourceManager.GetString("DeviceExceptionSimpleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя устройства.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя уcтройства 1.
        /// </summary>
        internal static string DeviceNameExample {
            get {
                return ResourceManager.GetString("DeviceNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название должно содержать символы или цифры и длина вводимого текста не должна превышать 20 символов.
        /// </summary>
        internal static string DeviceNameTooltip {
            get {
                return ResourceManager.GetString("DeviceNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя устройства не задано.
        /// </summary>
        internal static string DeviceNameValidationNotSet {
            get {
                return ResourceManager.GetString("DeviceNameValidationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя устройства должно содержать от 2-х до 20-ти символов..
        /// </summary>
        internal static string DeviceNameValidationRange {
            get {
                return ResourceManager.GetString("DeviceNameValidationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string DownSymbol {
            get {
                return ResourceManager.GetString("DownSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Драйвер с такими параметрами уже существует. Хост {0}, Порт {1}.
        /// </summary>
        internal static string DriverAlreadyExistsExceptionMessageFormat {
            get {
                return ResourceManager.GetString("DriverAlreadyExistsExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Драйвер таблицы данных.
        /// </summary>
        internal static string DriverDataTable {
            get {
                return ResourceManager.GetString("DriverDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка в таблице данных драйвера с идентификатором {0} уже существует.
        /// </summary>
        internal static string DriverDataTableDataRowExistsExceptionMessageFormat {
            get {
                return ResourceManager.GetString("DriverDataTableDataRowExistsExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в драйвере: {0}..
        /// </summary>
        internal static string DriverExceptionInfoPartMessageFormat {
            get {
                return ResourceManager.GetString("DriverExceptionInfoPartMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена ошибка при работе с драйвером..
        /// </summary>
        internal static string DriverExceptionSimpleMessage {
            get {
                return ResourceManager.GetString("DriverExceptionSimpleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Драйвер с идентификатором {0} не имеет таблицы данных для настройки.
        /// </summary>
        internal static string DriverNotHaveDataTableSetup {
            get {
                return ResourceManager.GetString("DriverNotHaveDataTableSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string EditSelectedDeviceHeader {
            get {
                return ResourceManager.GetString("EditSelectedDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вечернее.
        /// </summary>
        internal static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От:.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string HelpHeader {
            get {
                return ResourceManager.GetString("HelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иллюминация.
        /// </summary>
        internal static string Illumination {
            get {
                return ResourceManager.GetString("Illumination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string IpAddressExample {
            get {
                return ResourceManager.GetString("IpAddressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат IP адреса устройства.
        /// </summary>
        internal static string IpAddressValidationFormat {
            get {
                return ResourceManager.GetString("IpAddressValidationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP адрес устройства не задан.
        /// </summary>
        internal static string IpAddressValidationNotSet {
            get {
                return ResourceManager.GetString("IpAddressValidationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP порт устройства имеет неверный формат.
        /// </summary>
        internal static string IpPortValidationFormat {
            get {
                return ResourceManager.GetString("IpPortValidationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP порт устройства задан.
        /// </summary>
        internal static string IpPortValidationNotSet {
            get {
                return ResourceManager.GetString("IpPortValidationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP порт устройства должен быть в пределах от 0 до 9999.
        /// </summary>
        internal static string IpPortValidationRange {
            get {
                return ResourceManager.GetString("IpPortValidationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал системы.
        /// </summary>
        internal static string JournalOfSystemsHeader {
            get {
                return ResourceManager.GetString("JournalOfSystemsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        internal static string LogDescription {
            get {
                return ResourceManager.GetString("LogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ручной режим.
        /// </summary>
        internal static string ManualmodeCommand {
            get {
                return ResourceManager.GetString("ManualmodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое.
        /// </summary>
        internal static string NewDeviceHeader {
            get {
                return ResourceManager.GetString("NewDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ночное.
        /// </summary>
        internal static string Nighlighting {
            get {
                return ResourceManager.GetString("Nighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ассоциируемый драйвер с текущим устройством не найден.
        /// </summary>
        internal static string NoAssociatedDriverExceptionMessage {
            get {
                return ResourceManager.GetString("NoAssociatedDriverExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string NoButtonContent {
            get {
                return ResourceManager.GetString("NoButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство не найдено.
        /// </summary>
        internal static string NoDeviceDetected {
            get {
                return ResourceManager.GetString("NoDeviceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функционал устройства не реализован для режиме конфигурации..
        /// </summary>
        internal static string NoDeviceForConfigurationExceptionMessage {
            get {
                return ResourceManager.GetString("NoDeviceForConfigurationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройства не найдены.
        /// </summary>
        internal static string NoDevicesDetected {
            get {
                return ResourceManager.GetString("NoDevicesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраненный слой не может получить доступ к драйверу с  ID:.
        /// </summary>
        internal static string NotAccessFromPersistableToDriver {
            get {
                return ResourceManager.GetString("NotAccessFromPersistableToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно восстановить состояние драйвера с идентификатором:.
        /// </summary>
        internal static string NotRestoreStateOfDriver {
            get {
                return ResourceManager.GetString("NotRestoreStateOfDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет возможности работать с драйвером типа:.
        /// </summary>
        internal static string NotWorkWithDriverType {
            get {
                return ResourceManager.GetString("NotWorkWithDriverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkButtonContent {
            get {
                return ResourceManager.GetString("OkButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4444.
        /// </summary>
        internal static string PortExample {
            get {
                return ResourceManager.GetString("PortExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Устройство находится в режиме ремонта. Управление недоступно&quot;.
        /// </summary>
        internal static string RepairDefand {
            get {
                return ResourceManager.GetString("RepairDefand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита.
        /// </summary>
        internal static string RepairDefandTitle {
            get {
                return ResourceManager.GetString("RepairDefandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим реального времени.
        /// </summary>
        internal static string RuntimeMode {
            get {
                return ResourceManager.GetString("RuntimeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить все.
        /// </summary>
        internal static string StartAll {
            get {
                return ResourceManager.GetString("StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда не может быть послана.
        /// </summary>
        internal static string StarterNoExistMessage {
            get {
                return ResourceManager.GetString("StarterNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пускатели.
        /// </summary>
        internal static string Starters {
            get {
                return ResourceManager.GetString("Starters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить все.
        /// </summary>
        internal static string StopAll {
            get {
                return ResourceManager.GetString("StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергосбережение.
        /// </summary>
        internal static string StoregEnergy {
            get {
                return ResourceManager.GetString("StoregEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string SubmitCreateButtonContent {
            get {
                return ResourceManager.GetString("SubmitCreateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация времени.
        /// </summary>
        internal static string SynchronizationTimeTitle {
            get {
                return ResourceManager.GetString("SynchronizationTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизировать.
        /// </summary>
        internal static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip - адрес устройства.
        /// </summary>
        internal static string TcpIpAddress {
            get {
                return ResourceManager.GetString("TcpIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт виртуального устройства. Применяется валидация свойственная TCP/IP порту..
        /// </summary>
        internal static string TcpIpAddressTooltip {
            get {
                return ResourceManager.GetString("TcpIpAddressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт устройства.
        /// </summary>
        internal static string TcpIpPort {
            get {
                return ResourceManager.GetString("TcpIpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Драйвер (TCP Modbus).
        /// </summary>
        internal static string TCPModbusDriverSettings {
            get {
                return ResourceManager.GetString("TCPModbusDriverSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-адрес виртуального устройства. Применяется валидация свойственная для IP-адреса. Части адреса должны быть разделены точками (&apos;.&apos;)..
        /// </summary>
        internal static string TCPModbusDriverSettingsTooltip {
            get {
                return ResourceManager.GetString("TCPModbusDriverSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация времени.
        /// </summary>
        internal static string TimeSynchronizationHeader {
            get {
                return ResourceManager.GetString("TimeSynchronizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До:.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время выполнения операции обнаружена ошибка: {0}.
        /// </summary>
        internal static string UnexpectedErrorMessagePattern {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessagePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип устройства {0} не найдет в системе..
        /// </summary>
        internal static string UnknownDeviceTypeExceptionMessageFormat {
            get {
                return ResourceManager.GetString("UnknownDeviceTypeExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип драйвера {0} не найдет в системе..
        /// </summary>
        internal static string UnknownDriverTypeExceptionMessageFormat {
            get {
                return ResourceManager.GetString("UnknownDriverTypeExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string UpSymbol {
            get {
                return ResourceManager.GetString("UpSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество ошибок: {0}.
        /// </summary>
        internal static string ValidationTemplate {
            get {
                return ResourceManager.GetString("ValidationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия 5.0.
        /// </summary>
        internal static string VersionProgram {
            get {
                return ResourceManager.GetString("VersionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на схему.
        /// </summary>
        internal static string ViewSelectedDeviceSchemaHeader {
            get {
                return ResourceManager.GetString("ViewSelectedDeviceSchemaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство.
        /// </summary>
        internal static string VirtualDeviceHeader {
            get {
                return ResourceManager.GetString("VirtualDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт загрузка. Ожидайте.....
        /// </summary>
        internal static string WaitingBusyDialogMessage {
            get {
                return ResourceManager.GetString("WaitingBusyDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите создать новое устройство?.
        /// </summary>
        internal static string WantCreateDevice {
            get {
                return ResourceManager.GetString("WantCreateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите ли вы создать новое устройство?.
        /// </summary>
        internal static string WantToCreateNewDevice {
            get {
                return ResourceManager.GetString("WantToCreateNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string YesButtonContent {
            get {
                return ResourceManager.GetString("YesButtonContent", resourceCulture);
            }
        }
    }
}
