//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULA.Devices.PICONGS.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ULA.Devices.PICONGS.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Драйвер таблицы данных.
        /// </summary>
        internal static string DriverDataTable {
            get {
                return ResourceManager.GetString("DriverDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Драйвер с идентификатором {0} не имеет таблицы данных для настройки.
        /// </summary>
        internal static string DriverNotHaveDataTableSetup {
            get {
                return ResourceManager.GetString("DriverNotHaveDataTableSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ассоциируемый драйвер с текущим устройством не найден.
        /// </summary>
        internal static string NoAssociatedDriverExceptionMessage {
            get {
                return ResourceManager.GetString("NoAssociatedDriverExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраненный слой не может получить доступ к драйверу с  ID:.
        /// </summary>
        internal static string NotAccessFromPersistableToDriver {
            get {
                return ResourceManager.GetString("NotAccessFromPersistableToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно восстановить состояние драйвера с идентификатором:.
        /// </summary>
        internal static string NotRestoreStateOfDriver {
            get {
                return ResourceManager.GetString("NotRestoreStateOfDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет возможности работать с драйвером типа: .
        /// </summary>
        internal static string NotWorkWithDriverType {
            get {
                return ResourceManager.GetString("NotWorkWithDriverType", resourceCulture);
            }
        }
    }
}
